// Code generated by protoc-gen-go.
// source: comm.proto
// DO NOT EDIT!

/*
Package protomsg is a generated protocol buffer package.

It is generated from these files:
	comm.proto
	main_command.proto

It has these top-level messages:
	PBHeartBeat
	PBCommACK
	PBCommANK
	PBCommUserInfo
	PBCommUserInforChangeNotify
*/
package protomsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ??IDPB_MAIN_COMM = 1;// ??????
// ??ID????
type PB_SUB_COMM int32

const (
	PB_SUB_COMM_PB_SUB_COMM_HEART_BEAT       PB_SUB_COMM = 0
	PB_SUB_COMM_PB_SUB_COMM_ACK              PB_SUB_COMM = 1
	PB_SUB_COMM_PB_SUB_COMM_ANK              PB_SUB_COMM = 2
	PB_SUB_COMM_PB_SUB_COMM_USER_INFO_CHANGE PB_SUB_COMM = 3
)

var PB_SUB_COMM_name = map[int32]string{
	0: "PB_SUB_COMM_HEART_BEAT",
	1: "PB_SUB_COMM_ACK",
	2: "PB_SUB_COMM_ANK",
	3: "PB_SUB_COMM_USER_INFO_CHANGE",
}
var PB_SUB_COMM_value = map[string]int32{
	"PB_SUB_COMM_HEART_BEAT":       0,
	"PB_SUB_COMM_ACK":              1,
	"PB_SUB_COMM_ANK":              2,
	"PB_SUB_COMM_USER_INFO_CHANGE": 3,
}

func (x PB_SUB_COMM) String() string {
	return proto.EnumName(PB_SUB_COMM_name, int32(x))
}
func (PB_SUB_COMM) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// ???????????????????????0??????12
type PB_EN_MSG_PROCESS_STEP int32

const (
	PB_EN_MSG_PROCESS_STEP_EN_MSG_PROCESS_STEP_INIT PB_EN_MSG_PROCESS_STEP = 0
	PB_EN_MSG_PROCESS_STEP_EN_MSG_PROCESS_STEP_SYNC PB_EN_MSG_PROCESS_STEP = 12
)

var PB_EN_MSG_PROCESS_STEP_name = map[int32]string{
	0:  "EN_MSG_PROCESS_STEP_INIT",
	12: "EN_MSG_PROCESS_STEP_SYNC",
}
var PB_EN_MSG_PROCESS_STEP_value = map[string]int32{
	"EN_MSG_PROCESS_STEP_INIT": 0,
	"EN_MSG_PROCESS_STEP_SYNC": 12,
}

func (x PB_EN_MSG_PROCESS_STEP) String() string {
	return proto.EnumName(PB_EN_MSG_PROCESS_STEP_name, int32(x))
}
func (PB_EN_MSG_PROCESS_STEP) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// [START messages]
// 1,0
type PBHeartBeat struct {
	ICurStep int32 `protobuf:"varint,1,opt,name=iCurStep" json:"iCurStep,omitempty"`
}

func (m *PBHeartBeat) Reset()                    { *m = PBHeartBeat{} }
func (m *PBHeartBeat) String() string            { return proto.CompactTextString(m) }
func (*PBHeartBeat) ProtoMessage()               {}
func (*PBHeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PBHeartBeat) GetICurStep() int32 {
	if m != nil {
		return m.ICurStep
	}
	return 0
}

// 1,1  ????????????????
type PBCommACK struct {
	WMainCmdID int32  `protobuf:"varint,1,opt,name=wMainCmdID" json:"wMainCmdID,omitempty"`
	WSubCmdID  int32  `protobuf:"varint,2,opt,name=wSubCmdID" json:"wSubCmdID,omitempty"`
	DwExp      uint32 `protobuf:"varint,3,opt,name=dwExp" json:"dwExp,omitempty"`
}

func (m *PBCommACK) Reset()                    { *m = PBCommACK{} }
func (m *PBCommACK) String() string            { return proto.CompactTextString(m) }
func (*PBCommACK) ProtoMessage()               {}
func (*PBCommACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PBCommACK) GetWMainCmdID() int32 {
	if m != nil {
		return m.WMainCmdID
	}
	return 0
}

func (m *PBCommACK) GetWSubCmdID() int32 {
	if m != nil {
		return m.WSubCmdID
	}
	return 0
}

func (m *PBCommACK) GetDwExp() uint32 {
	if m != nil {
		return m.DwExp
	}
	return 0
}

// 1,2  ????????????????
type PBCommANK struct {
	WMainCmdID int32  `protobuf:"varint,1,opt,name=wMainCmdID" json:"wMainCmdID,omitempty"`
	WSubCmdID  int32  `protobuf:"varint,2,opt,name=wSubCmdID" json:"wSubCmdID,omitempty"`
	DwExp      uint32 `protobuf:"varint,3,opt,name=dwExp" json:"dwExp,omitempty"`
	DwErrCode  uint32 `protobuf:"varint,4,opt,name=dwErrCode" json:"dwErrCode,omitempty"`
}

func (m *PBCommANK) Reset()                    { *m = PBCommANK{} }
func (m *PBCommANK) String() string            { return proto.CompactTextString(m) }
func (*PBCommANK) ProtoMessage()               {}
func (*PBCommANK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PBCommANK) GetWMainCmdID() int32 {
	if m != nil {
		return m.WMainCmdID
	}
	return 0
}

func (m *PBCommANK) GetWSubCmdID() int32 {
	if m != nil {
		return m.WSubCmdID
	}
	return 0
}

func (m *PBCommANK) GetDwExp() uint32 {
	if m != nil {
		return m.DwExp
	}
	return 0
}

func (m *PBCommANK) GetDwErrCode() uint32 {
	if m != nil {
		return m.DwErrCode
	}
	return 0
}

// ?????????????????
type PBCommUserInfo struct {
	DwUserID     uint32 `protobuf:"varint,1,opt,name=dwUserID" json:"dwUserID,omitempty"`
	SzName       string `protobuf:"bytes,2,opt,name=szName" json:"szName,omitempty"`
	SzPasswd     string `protobuf:"bytes,3,opt,name=szPasswd" json:"szPasswd,omitempty"`
	SzNicName    string `protobuf:"bytes,4,opt,name=szNicName" json:"szNicName,omitempty"`
	SzUserPic    string `protobuf:"bytes,5,opt,name=szUserPic" json:"szUserPic,omitempty"`
	BtSex        int32  `protobuf:"varint,6,opt,name=btSex" json:"btSex,omitempty"`
	BtStatus     int32  `protobuf:"varint,7,opt,name=btStatus" json:"btStatus,omitempty"`
	BtRenZhen    int32  `protobuf:"varint,8,opt,name=btRenZhen" json:"btRenZhen,omitempty"`
	DwCreateTime uint32 `protobuf:"varint,9,opt,name=dwCreateTime" json:"dwCreateTime,omitempty"`
	DwUpdateTime uint32 `protobuf:"varint,10,opt,name=dwUpdateTime" json:"dwUpdateTime,omitempty"`
	// t_user_expand
	LlEnergyCounts  int64  `protobuf:"varint,11,opt,name=llEnergyCounts" json:"llEnergyCounts,omitempty"`
	LlInteralCounts int64  `protobuf:"varint,12,opt,name=llInteralCounts" json:"llInteralCounts,omitempty"`
	WVersion        uint32 `protobuf:"varint,13,opt,name=wVersion" json:"wVersion,omitempty"`
	LlLockInteral   int64  `protobuf:"varint,14,opt,name=llLockInteral" json:"llLockInteral,omitempty"`
	// t_statist
	LlEnergy_1    int64  `protobuf:"varint,15,opt,name=llEnergy_1,json=llEnergy1" json:"llEnergy_1,omitempty"`
	LlEnergy_2    int64  `protobuf:"varint,16,opt,name=llEnergy_2,json=llEnergy2" json:"llEnergy_2,omitempty"`
	LlEnergy_3    int64  `protobuf:"varint,17,opt,name=llEnergy_3,json=llEnergy3" json:"llEnergy_3,omitempty"`
	LlEnergy_Max  int64  `protobuf:"varint,18,opt,name=llEnergy_Max,json=llEnergyMax" json:"llEnergy_Max,omitempty"`
	LlInteral_1   int64  `protobuf:"varint,19,opt,name=llInteral_1,json=llInteral1" json:"llInteral_1,omitempty"`
	LlInteral_2   int64  `protobuf:"varint,20,opt,name=llInteral_2,json=llInteral2" json:"llInteral_2,omitempty"`
	LlInteral_3   int64  `protobuf:"varint,21,opt,name=llInteral_3,json=llInteral3" json:"llInteral_3,omitempty"`
	LlInteral_Max int64  `protobuf:"varint,22,opt,name=llInteral_Max,json=llInteralMax" json:"llInteral_Max,omitempty"`
	DwEnergyLev   uint32 `protobuf:"varint,23,opt,name=dwEnergyLev" json:"dwEnergyLev,omitempty"`
	DwInteralLev  uint32 `protobuf:"varint,24,opt,name=dwInteralLev" json:"dwInteralLev,omitempty"`
	DwRedLev      uint32 `protobuf:"varint,25,opt,name=dwRedLev" json:"dwRedLev,omitempty"`
	DwYellowLev   uint32 `protobuf:"varint,26,opt,name=dwYellowLev" json:"dwYellowLev,omitempty"`
	DwRedStars    uint32 `protobuf:"varint,27,opt,name=dwRedStars" json:"dwRedStars,omitempty"`
	DwYelloStars  uint32 `protobuf:"varint,28,opt,name=dwYelloStars" json:"dwYelloStars,omitempty"`
	WCustomAccout uint32 `protobuf:"varint,29,opt,name=wCustomAccout" json:"wCustomAccout,omitempty"`
	WVip          uint32 `protobuf:"varint,30,opt,name=wVip" json:"wVip,omitempty"`
	// ????????????????
	DLongiTude     float64 `protobuf:"fixed64,31,opt,name=dLongiTude" json:"dLongiTude,omitempty"`
	DLatitude      float64 `protobuf:"fixed64,32,opt,name=dLatitude" json:"dLatitude,omitempty"`
	DwBirthDay     uint32  `protobuf:"varint,33,opt,name=dwBirthDay" json:"dwBirthDay,omitempty"`
	DwLastSn       uint32  `protobuf:"varint,34,opt,name=dwLastSn" json:"dwLastSn,omitempty"`
	DwPriPicLevel  uint32  `protobuf:"varint,35,opt,name=dwPriPicLevel" json:"dwPriPicLevel,omitempty"`
	DwPriPicCounts uint32  `protobuf:"varint,36,opt,name=dwPriPicCounts" json:"dwPriPicCounts,omitempty"`
	// ?????????????????????????????
	LlEnergyValue   int64 `protobuf:"varint,37,opt,name=llEnergyValue" json:"llEnergyValue,omitempty"`
	LlIntegralValue int64 `protobuf:"varint,38,opt,name=llIntegralValue" json:"llIntegralValue,omitempty"`
	// ??????????????????????????????????????????????????????VIP??????????????????????????????M,?????V ????????????????????????????
	// ????????????????????
	DwEnergyValueLev   uint32 `protobuf:"varint,39,opt,name=dwEnergyValueLev" json:"dwEnergyValueLev,omitempty"`
	DwIntegralValueLev uint32 `protobuf:"varint,40,opt,name=dwIntegralValueLev" json:"dwIntegralValueLev,omitempty"`
	// ???? ??????? ???????? t_statist  ->energycounts_lev
	DwEnergyCountsLev uint32 `protobuf:"varint,41,opt,name=dwEnergyCountsLev" json:"dwEnergyCountsLev,omitempty"`
	// ??????????
	DRechargeValue float64 `protobuf:"fixed64,42,opt,name=dRechargeValue" json:"dRechargeValue,omitempty"`
}

func (m *PBCommUserInfo) Reset()                    { *m = PBCommUserInfo{} }
func (m *PBCommUserInfo) String() string            { return proto.CompactTextString(m) }
func (*PBCommUserInfo) ProtoMessage()               {}
func (*PBCommUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PBCommUserInfo) GetDwUserID() uint32 {
	if m != nil {
		return m.DwUserID
	}
	return 0
}

func (m *PBCommUserInfo) GetSzName() string {
	if m != nil {
		return m.SzName
	}
	return ""
}

func (m *PBCommUserInfo) GetSzPasswd() string {
	if m != nil {
		return m.SzPasswd
	}
	return ""
}

func (m *PBCommUserInfo) GetSzNicName() string {
	if m != nil {
		return m.SzNicName
	}
	return ""
}

func (m *PBCommUserInfo) GetSzUserPic() string {
	if m != nil {
		return m.SzUserPic
	}
	return ""
}

func (m *PBCommUserInfo) GetBtSex() int32 {
	if m != nil {
		return m.BtSex
	}
	return 0
}

func (m *PBCommUserInfo) GetBtStatus() int32 {
	if m != nil {
		return m.BtStatus
	}
	return 0
}

func (m *PBCommUserInfo) GetBtRenZhen() int32 {
	if m != nil {
		return m.BtRenZhen
	}
	return 0
}

func (m *PBCommUserInfo) GetDwCreateTime() uint32 {
	if m != nil {
		return m.DwCreateTime
	}
	return 0
}

func (m *PBCommUserInfo) GetDwUpdateTime() uint32 {
	if m != nil {
		return m.DwUpdateTime
	}
	return 0
}

func (m *PBCommUserInfo) GetLlEnergyCounts() int64 {
	if m != nil {
		return m.LlEnergyCounts
	}
	return 0
}

func (m *PBCommUserInfo) GetLlInteralCounts() int64 {
	if m != nil {
		return m.LlInteralCounts
	}
	return 0
}

func (m *PBCommUserInfo) GetWVersion() uint32 {
	if m != nil {
		return m.WVersion
	}
	return 0
}

func (m *PBCommUserInfo) GetLlLockInteral() int64 {
	if m != nil {
		return m.LlLockInteral
	}
	return 0
}

func (m *PBCommUserInfo) GetLlEnergy_1() int64 {
	if m != nil {
		return m.LlEnergy_1
	}
	return 0
}

func (m *PBCommUserInfo) GetLlEnergy_2() int64 {
	if m != nil {
		return m.LlEnergy_2
	}
	return 0
}

func (m *PBCommUserInfo) GetLlEnergy_3() int64 {
	if m != nil {
		return m.LlEnergy_3
	}
	return 0
}

func (m *PBCommUserInfo) GetLlEnergy_Max() int64 {
	if m != nil {
		return m.LlEnergy_Max
	}
	return 0
}

func (m *PBCommUserInfo) GetLlInteral_1() int64 {
	if m != nil {
		return m.LlInteral_1
	}
	return 0
}

func (m *PBCommUserInfo) GetLlInteral_2() int64 {
	if m != nil {
		return m.LlInteral_2
	}
	return 0
}

func (m *PBCommUserInfo) GetLlInteral_3() int64 {
	if m != nil {
		return m.LlInteral_3
	}
	return 0
}

func (m *PBCommUserInfo) GetLlInteral_Max() int64 {
	if m != nil {
		return m.LlInteral_Max
	}
	return 0
}

func (m *PBCommUserInfo) GetDwEnergyLev() uint32 {
	if m != nil {
		return m.DwEnergyLev
	}
	return 0
}

func (m *PBCommUserInfo) GetDwInteralLev() uint32 {
	if m != nil {
		return m.DwInteralLev
	}
	return 0
}

func (m *PBCommUserInfo) GetDwRedLev() uint32 {
	if m != nil {
		return m.DwRedLev
	}
	return 0
}

func (m *PBCommUserInfo) GetDwYellowLev() uint32 {
	if m != nil {
		return m.DwYellowLev
	}
	return 0
}

func (m *PBCommUserInfo) GetDwRedStars() uint32 {
	if m != nil {
		return m.DwRedStars
	}
	return 0
}

func (m *PBCommUserInfo) GetDwYelloStars() uint32 {
	if m != nil {
		return m.DwYelloStars
	}
	return 0
}

func (m *PBCommUserInfo) GetWCustomAccout() uint32 {
	if m != nil {
		return m.WCustomAccout
	}
	return 0
}

func (m *PBCommUserInfo) GetWVip() uint32 {
	if m != nil {
		return m.WVip
	}
	return 0
}

func (m *PBCommUserInfo) GetDLongiTude() float64 {
	if m != nil {
		return m.DLongiTude
	}
	return 0
}

func (m *PBCommUserInfo) GetDLatitude() float64 {
	if m != nil {
		return m.DLatitude
	}
	return 0
}

func (m *PBCommUserInfo) GetDwBirthDay() uint32 {
	if m != nil {
		return m.DwBirthDay
	}
	return 0
}

func (m *PBCommUserInfo) GetDwLastSn() uint32 {
	if m != nil {
		return m.DwLastSn
	}
	return 0
}

func (m *PBCommUserInfo) GetDwPriPicLevel() uint32 {
	if m != nil {
		return m.DwPriPicLevel
	}
	return 0
}

func (m *PBCommUserInfo) GetDwPriPicCounts() uint32 {
	if m != nil {
		return m.DwPriPicCounts
	}
	return 0
}

func (m *PBCommUserInfo) GetLlEnergyValue() int64 {
	if m != nil {
		return m.LlEnergyValue
	}
	return 0
}

func (m *PBCommUserInfo) GetLlIntegralValue() int64 {
	if m != nil {
		return m.LlIntegralValue
	}
	return 0
}

func (m *PBCommUserInfo) GetDwEnergyValueLev() uint32 {
	if m != nil {
		return m.DwEnergyValueLev
	}
	return 0
}

func (m *PBCommUserInfo) GetDwIntegralValueLev() uint32 {
	if m != nil {
		return m.DwIntegralValueLev
	}
	return 0
}

func (m *PBCommUserInfo) GetDwEnergyCountsLev() uint32 {
	if m != nil {
		return m.DwEnergyCountsLev
	}
	return 0
}

func (m *PBCommUserInfo) GetDRechargeValue() float64 {
	if m != nil {
		return m.DRechargeValue
	}
	return 0
}

// 1,3
type PBCommUserInforChangeNotify struct {
	DwUserId             uint32 `protobuf:"varint,1,opt,name=dwUserId" json:"dwUserId,omitempty"`
	DwRelativeUserId     uint32 `protobuf:"varint,2,opt,name=dwRelativeUserId" json:"dwRelativeUserId,omitempty"`
	LlEneryCounts        int64  `protobuf:"varint,3,opt,name=llEneryCounts" json:"llEneryCounts,omitempty"`
	LlIntegralCounts     int64  `protobuf:"varint,4,opt,name=llIntegralCounts" json:"llIntegralCounts,omitempty"`
	LlGiveEnergyCounts   int64  `protobuf:"varint,5,opt,name=llGiveEnergyCounts" json:"llGiveEnergyCounts,omitempty"`
	LlGiveIntegralCounts int64  `protobuf:"varint,6,opt,name=llGiveIntegralCounts" json:"llGiveIntegralCounts,omitempty"`
	LlGiveChangeEnValue  int64  `protobuf:"varint,7,opt,name=llGiveChangeEnValue" json:"llGiveChangeEnValue,omitempty"`
	LlGiveChangeInValue  int64  `protobuf:"varint,8,opt,name=llGiveChangeInValue" json:"llGiveChangeInValue,omitempty"`
	// ?????????????????????????????
	LlChangeEnergyValue   int64 `protobuf:"varint,9,opt,name=llChangeEnergyValue" json:"llChangeEnergyValue,omitempty"`
	LlChangeIntegralValue int64 `protobuf:"varint,10,opt,name=llChangeIntegralValue" json:"llChangeIntegralValue,omitempty"`
	// ????????????
	IChangeType int32 `protobuf:"varint,11,opt,name=iChangeType" json:"iChangeType,omitempty"`
	IReason     int32 `protobuf:"varint,12,opt,name=iReason" json:"iReason,omitempty"`
}

func (m *PBCommUserInforChangeNotify) Reset()                    { *m = PBCommUserInforChangeNotify{} }
func (m *PBCommUserInforChangeNotify) String() string            { return proto.CompactTextString(m) }
func (*PBCommUserInforChangeNotify) ProtoMessage()               {}
func (*PBCommUserInforChangeNotify) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PBCommUserInforChangeNotify) GetDwUserId() uint32 {
	if m != nil {
		return m.DwUserId
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetDwRelativeUserId() uint32 {
	if m != nil {
		return m.DwRelativeUserId
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetLlEneryCounts() int64 {
	if m != nil {
		return m.LlEneryCounts
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetLlIntegralCounts() int64 {
	if m != nil {
		return m.LlIntegralCounts
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetLlGiveEnergyCounts() int64 {
	if m != nil {
		return m.LlGiveEnergyCounts
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetLlGiveIntegralCounts() int64 {
	if m != nil {
		return m.LlGiveIntegralCounts
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetLlGiveChangeEnValue() int64 {
	if m != nil {
		return m.LlGiveChangeEnValue
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetLlGiveChangeInValue() int64 {
	if m != nil {
		return m.LlGiveChangeInValue
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetLlChangeEnergyValue() int64 {
	if m != nil {
		return m.LlChangeEnergyValue
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetLlChangeIntegralValue() int64 {
	if m != nil {
		return m.LlChangeIntegralValue
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetIChangeType() int32 {
	if m != nil {
		return m.IChangeType
	}
	return 0
}

func (m *PBCommUserInforChangeNotify) GetIReason() int32 {
	if m != nil {
		return m.IReason
	}
	return 0
}

func init() {
	proto.RegisterType((*PBHeartBeat)(nil), "pb_comm.PBHeartBeat")
	proto.RegisterType((*PBCommACK)(nil), "pb_comm.PBCommACK")
	proto.RegisterType((*PBCommANK)(nil), "pb_comm.PBCommANK")
	proto.RegisterType((*PBCommUserInfo)(nil), "pb_comm.PBCommUserInfo")
	proto.RegisterType((*PBCommUserInforChangeNotify)(nil), "pb_comm.PBCommUserInforChangeNotify")
	proto.RegisterEnum("pb_comm.PB_SUB_COMM", PB_SUB_COMM_name, PB_SUB_COMM_value)
	proto.RegisterEnum("pb_comm.PB_EN_MSG_PROCESS_STEP", PB_EN_MSG_PROCESS_STEP_name, PB_EN_MSG_PROCESS_STEP_value)
}

func init() { proto.RegisterFile("comm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1035 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x5d, 0x53, 0xdb, 0x46,
	0x17, 0xc7, 0x1f, 0x03, 0x06, 0xbc, 0xe6, 0xc5, 0x59, 0x08, 0xcf, 0x96, 0x90, 0xc4, 0x71, 0xd2,
	0xd4, 0xa1, 0x1d, 0xa6, 0x40, 0xbf, 0x80, 0xad, 0xa8, 0xe0, 0xc1, 0x36, 0x1e, 0xc9, 0x30, 0x93,
	0xdc, 0x68, 0xd6, 0xd6, 0x62, 0x34, 0x95, 0x25, 0x8f, 0xb4, 0x42, 0x98, 0x99, 0x7e, 0x93, 0xde,
	0xf5, 0x8b, 0x76, 0xf6, 0xac, 0x56, 0x2f, 0xb6, 0x7b, 0xd9, 0x3b, 0x9f, 0xdf, 0xff, 0x7f, 0x74,
	0xce, 0x9e, 0xd5, 0xae, 0x85, 0xd0, 0xd8, 0x9f, 0x4e, 0xcf, 0x66, 0x81, 0xcf, 0x7d, 0xbc, 0x35,
	0x1b, 0x59, 0x22, 0x6c, 0x7c, 0x41, 0xd5, 0x41, 0xfb, 0x9a, 0xd1, 0x80, 0xb7, 0x19, 0xe5, 0xf8,
	0x18, 0x6d, 0x3b, 0x5a, 0x14, 0x98, 0x9c, 0xcd, 0x48, 0xa9, 0x5e, 0x6a, 0x96, 0x8d, 0x34, 0x6e,
	0x58, 0xa8, 0x32, 0x68, 0x6b, 0xfe, 0x74, 0xda, 0xd2, 0x6e, 0xf0, 0x3b, 0x84, 0xe2, 0x1e, 0x75,
	0x3c, 0x6d, 0x6a, 0x77, 0xbe, 0x26, 0xd6, 0x1c, 0xc1, 0x27, 0xa8, 0x12, 0x9b, 0xd1, 0x48, 0xca,
	0x6b, 0x20, 0x67, 0x00, 0x1f, 0xa2, 0xb2, 0x1d, 0xeb, 0xcf, 0x33, 0xb2, 0x5e, 0x2f, 0x35, 0x77,
	0x0d, 0x19, 0x34, 0xfe, 0x4c, 0x0b, 0xf4, 0xff, 0x93, 0x02, 0x22, 0xc7, 0x8e, 0xf5, 0x20, 0xd0,
	0x7c, 0x9b, 0x91, 0x0d, 0x50, 0x32, 0xd0, 0xf8, 0xab, 0x8a, 0xf6, 0x64, 0xfd, 0xbb, 0x90, 0x05,
	0x1d, 0xef, 0xc1, 0x17, 0xe3, 0xb0, 0x63, 0x88, 0x64, 0x0b, 0xbb, 0x46, 0x1a, 0xe3, 0x23, 0xb4,
	0x19, 0xbe, 0xf4, 0xe9, 0x94, 0x41, 0xf5, 0x8a, 0x91, 0x44, 0x22, 0x27, 0x7c, 0x19, 0xd0, 0x30,
	0x8c, 0x6d, 0xa8, 0x5e, 0x31, 0xd2, 0x58, 0x34, 0x10, 0xbe, 0xf4, 0x9d, 0x31, 0xa4, 0x6d, 0x80,
	0x98, 0x01, 0xa9, 0x8a, 0xa7, 0x0f, 0x9c, 0x31, 0x29, 0x2b, 0x35, 0x01, 0x62, 0x49, 0x23, 0x6e,
	0xb2, 0x67, 0xb2, 0x09, 0x8b, 0x95, 0x81, 0xa8, 0x36, 0xe2, 0x26, 0xa7, 0x3c, 0x0a, 0xc9, 0x96,
	0xdc, 0x30, 0x15, 0x8b, 0xe7, 0x8d, 0xb8, 0xc1, 0xbc, 0xef, 0x8f, 0xcc, 0x23, 0xdb, 0x72, 0x44,
	0x29, 0xc0, 0x0d, 0xb4, 0x63, 0xc7, 0x5a, 0xc0, 0x28, 0x67, 0x43, 0x67, 0xca, 0x48, 0x05, 0xd6,
	0x57, 0x60, 0xd2, 0x73, 0x37, 0xb3, 0x95, 0x07, 0x29, 0x4f, 0xc6, 0xf0, 0x67, 0xb4, 0xe7, 0xba,
	0xba, 0xc7, 0x82, 0xc9, 0x5c, 0xf3, 0x23, 0x8f, 0x87, 0xa4, 0x5a, 0x2f, 0x35, 0xd7, 0x8d, 0x05,
	0x8a, 0x9b, 0x68, 0xdf, 0x75, 0x3b, 0x1e, 0x67, 0x01, 0x75, 0x13, 0xe3, 0x0e, 0x18, 0x17, 0xb1,
	0x58, 0x53, 0x7c, 0xcf, 0x82, 0xd0, 0xf1, 0x3d, 0xb2, 0x2b, 0xa7, 0xae, 0x62, 0xfc, 0x09, 0xed,
	0xba, 0x6e, 0xd7, 0x1f, 0xff, 0x91, 0xa4, 0x90, 0x3d, 0x78, 0x46, 0x11, 0xe2, 0xb7, 0x08, 0xa9,
	0xea, 0xd6, 0x39, 0xd9, 0x07, 0x4b, 0x45, 0x91, 0xf3, 0x82, 0x7c, 0x41, 0x6a, 0x45, 0xf9, 0xa2,
	0x20, 0x5f, 0x92, 0x57, 0x45, 0xf9, 0x12, 0x7f, 0x40, 0x3b, 0xa9, 0xdc, 0xa3, 0xcf, 0x04, 0x83,
	0xa1, 0xaa, 0x58, 0x8f, 0x3e, 0xe3, 0xf7, 0xa8, 0x9a, 0x2e, 0xca, 0x3a, 0x27, 0x07, 0xe0, 0x40,
	0x29, 0x3a, 0x2f, 0x1a, 0x2e, 0xc8, 0xe1, 0x82, 0xe1, 0xa2, 0x68, 0xb8, 0x24, 0xaf, 0x17, 0x0c,
	0x97, 0xf8, 0xa3, 0x18, 0x84, 0x32, 0x88, 0x36, 0x8e, 0xc0, 0xb2, 0x93, 0x42, 0xd1, 0x47, 0x1d,
	0x55, 0xed, 0x58, 0xb6, 0xd5, 0x65, 0x4f, 0xe4, 0xff, 0x30, 0xcc, 0x3c, 0x92, 0x3b, 0x9c, 0x64,
	0x08, 0x0b, 0x51, 0x3b, 0x9c, 0x31, 0x79, 0x0a, 0x0c, 0x66, 0x0b, 0xfd, 0x07, 0x75, 0x0a, 0x64,
	0x2c, 0x2b, 0x7c, 0x63, 0xae, 0xeb, 0xc7, 0x42, 0x3e, 0x56, 0x15, 0x52, 0x24, 0x0e, 0x32, 0xb8,
	0x4d, 0x4e, 0x83, 0x90, 0xbc, 0x01, 0x43, 0x8e, 0xc8, 0x0e, 0xc0, 0x2e, 0x1d, 0x27, 0xaa, 0x83,
	0x8c, 0x89, 0x5d, 0x8f, 0xb5, 0x28, 0xe4, 0xfe, 0xb4, 0x35, 0x1e, 0xfb, 0x11, 0x27, 0x6f, 0xc1,
	0x54, 0x84, 0x18, 0xa3, 0x8d, 0xf8, 0xde, 0x99, 0x91, 0x77, 0x20, 0xc2, 0x6f, 0xa8, 0xde, 0xf5,
	0xbd, 0x89, 0x33, 0x8c, 0x6c, 0x46, 0xde, 0xd7, 0x4b, 0xcd, 0x92, 0x91, 0x23, 0x70, 0x25, 0x74,
	0x29, 0x77, 0xb8, 0x90, 0xeb, 0x20, 0x67, 0x40, 0xf6, 0xde, 0x76, 0x02, 0xfe, 0xf8, 0x95, 0xce,
	0xc9, 0x07, 0xd5, 0xbb, 0x22, 0x72, 0x32, 0x5d, 0x1a, 0x72, 0xd3, 0x23, 0x0d, 0x35, 0x19, 0x19,
	0x8b, 0x9e, 0xed, 0x78, 0x10, 0x38, 0x03, 0x67, 0xdc, 0x65, 0x4f, 0xcc, 0x25, 0x1f, 0x65, 0xcf,
	0x05, 0x28, 0x4e, 0x8f, 0x02, 0xc9, 0xa1, 0xf8, 0x04, 0xb6, 0x05, 0x2a, 0xdf, 0x7b, 0xb9, 0x6d,
	0xf7, 0xd4, 0x8d, 0x18, 0xf9, 0x51, 0xbd, 0xf7, 0x39, 0x98, 0x9d, 0xb1, 0x49, 0x40, 0x5d, 0xe9,
	0xfb, 0x9c, 0x3f, 0x63, 0x29, 0xc6, 0xa7, 0xa8, 0xa6, 0x5e, 0x03, 0x00, 0x62, 0xf3, 0x7e, 0x82,
	0xca, 0x4b, 0x1c, 0x9f, 0x21, 0x2c, 0xdf, 0x87, 0x34, 0x5d, 0xb8, 0x9b, 0xe0, 0x5e, 0xa1, 0xe0,
	0x5f, 0xd0, 0x2b, 0xf5, 0x0c, 0xd9, 0xbd, 0xb0, 0x7f, 0x01, 0xfb, 0xb2, 0x00, 0x13, 0x30, 0xd8,
	0xf8, 0x91, 0x06, 0x13, 0x26, 0x5b, 0x3e, 0x85, 0x6d, 0x58, 0xa0, 0x8d, 0xbf, 0x37, 0xd0, 0x9b,
	0xe2, 0xf5, 0x1c, 0x68, 0x8f, 0xd4, 0x9b, 0xb0, 0xbe, 0xcf, 0x9d, 0x87, 0x79, 0xee, 0xae, 0xb6,
	0x17, 0xee, 0x6a, 0x5b, 0xae, 0xd6, 0x60, 0x2e, 0xe5, 0xce, 0x13, 0x4b, 0x3c, 0x6b, 0x6a, 0xb5,
	0x45, 0x9e, 0x4d, 0x5a, 0x5d, 0x67, 0xeb, 0xf9, 0x49, 0xab, 0xdb, 0xec, 0x14, 0xd5, 0xb2, 0x91,
	0x26, 0xc6, 0x0d, 0x30, 0x2e, 0x71, 0x31, 0x3f, 0xd7, 0xbd, 0x72, 0x9e, 0x58, 0xe1, 0x96, 0x2c,
	0x83, 0x7b, 0x85, 0x82, 0x2f, 0xd0, 0xa1, 0xa4, 0x0b, 0xcf, 0xdf, 0x84, 0x8c, 0x95, 0x1a, 0xfe,
	0x15, 0x1d, 0x48, 0x2e, 0x67, 0xa2, 0x7b, 0x72, 0x94, 0x5b, 0x90, 0xb2, 0x4a, 0x5a, 0xcc, 0xe8,
	0x24, 0x19, 0xdb, 0xcb, 0x19, 0x9d, 0x7c, 0x86, 0x7a, 0x48, 0xf6, 0x26, 0x56, 0x54, 0xc6, 0x92,
	0x84, 0x7f, 0x43, 0xaf, 0x15, 0x2e, 0xbe, 0x95, 0x08, 0x72, 0x56, 0x8b, 0xe2, 0x4e, 0x71, 0x24,
	0x1f, 0xce, 0x67, 0x0c, 0xfe, 0x4e, 0xca, 0x46, 0x1e, 0x61, 0x82, 0xb6, 0x1c, 0x83, 0xd1, 0xd0,
	0xf7, 0xe0, 0x3f, 0xa4, 0x6c, 0xa8, 0xf0, 0x34, 0x12, 0xdf, 0x33, 0x96, 0x79, 0xd7, 0xb6, 0xb4,
	0xdb, 0x5e, 0x0f, 0x1f, 0xa3, 0xa3, 0x5c, 0x68, 0x5d, 0xeb, 0x2d, 0x63, 0x68, 0xb5, 0xf5, 0xd6,
	0xb0, 0xf6, 0x3f, 0x7c, 0x80, 0xf6, 0xf3, 0x5a, 0x4b, 0xbb, 0xa9, 0x95, 0x96, 0x60, 0xff, 0xa6,
	0xb6, 0x86, 0xeb, 0xe8, 0x24, 0x0f, 0xef, 0x4c, 0xdd, 0xb0, 0x3a, 0xfd, 0xdf, 0x6f, 0x2d, 0xed,
	0xba, 0xd5, 0xbf, 0xd2, 0x6b, 0xeb, 0xa7, 0x43, 0xa8, 0xa3, 0xf7, 0xad, 0x9e, 0x79, 0x65, 0x0d,
	0x8c, 0x5b, 0x4d, 0x37, 0x4d, 0xcb, 0x1c, 0xea, 0x03, 0x7c, 0x82, 0xc8, 0x0a, 0x6c, 0x75, 0xfa,
	0x1d, 0xd1, 0xc3, 0xbf, 0xa8, 0xe6, 0xb7, 0xbe, 0x56, 0xdb, 0x69, 0xff, 0x8c, 0x0e, 0xc7, 0xfe,
	0xf4, 0x6c, 0xce, 0xe5, 0x57, 0xdb, 0x28, 0x7a, 0x38, 0x13, 0x1f, 0x6d, 0xed, 0x8a, 0x38, 0x05,
	0x03, 0x81, 0xbe, 0x6f, 0x83, 0x32, 0x0d, 0x27, 0xa3, 0x4d, 0xf8, 0x75, 0xf9, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8b, 0x3a, 0x15, 0x3f, 0xe7, 0x09, 0x00, 0x00,
}
